name: youplan
description: A new Flutter application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_core: ^0.5.1
  firebase_auth: ^0.18.1+2
  cloud_firestore: ^0.14.1+3
  provider: ^4.1.3
  flutter_spinkit: ^4.1.2+1
  algolia: ^0.1.7
  font_awesome_flutter: ^8.8.1
  flare_flutter: ^2.0.3
  data_connection_checker: ^0.3.4
  google_maps_flutter: ^0.5.28+1
  geolocator: ^5.3.2+2
  flutter_google_places: ^0.2.5
  google_maps_webservice: ^0.0.17
  intl: ^0.16.1
  device_preview: ^0.4.7
  splashscreen: ^1.2.0
  cloud_functions: ^0.7.1
  intl_phone_field:
    git:
      url: https://github.com/AhmadWehbe167/intl_phone_field.git

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test:
  mockito: ^4.1.3

flutter:

  uses-material-design: true
  assets:
   - images/
   - animations/
  fonts:
   - family: Lobster
     fonts:
       - asset: fonts/Lobster-Regular.ttf
   - family: ArchitectsDaughter
     fonts:
       - asset: fonts/ArchitectsDaughter-Regular.ttf
   - family: ConcertOne
     fonts:
       - asset: fonts/ConcertOne-Regular.ttf
   - family: NotoSansJP
     fonts:
       - asset: fonts/NotoSansJP-Bold.otf

